name: Code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black isort

      - name: black with flake8
        run: |
          python -m flake8 --count --show-source --statistics --max-line-length 100 .
          python3 -m isort --profile black --check --diff .
          python3 -m black --check --diff  .
